repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.10.0
    hooks:
    -   id: reorder-python-imports

-   repo: https://github.com/psf/black
    rev: '23.7.0'
    hooks:
    -   id: black
        args:
            - "-S"
            - "-l"
            - "120"

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
    -   id: pyupgrade
        args: ["--py38-plus"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.4.1'
    hooks:
    -   id: mypy
        args:
            - "--strict"
            - "--disable-error-code"
            - "name-defined"
        exclude: ^(tests/.*|setup.py|docs/.*)
        additional_dependencies:
          - types-regex

-   repo: https://github.com/pycqa/flake8
    rev: '6.1.0'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        args:
          - "--ignore"
          - "E501,E704,E301,W503,F405,F811,F821,F403,"
